name: Build ARM Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install system dependencies and set environment
      run: |
        brew install espeak-ng cmake pkg-config
        # Set environment variables for ARM64 compilation
        echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPATH=/opt/homebrew/include:$CPATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/opt/homebrew/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L/opt/homebrew/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/homebrew/include" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools Cython numpy
        # Try to install piper-phonemize from source
        pip install --no-binary=piper-phonemize piper-phonemize --verbose
        pip install piper-tts==1.2.0
        pip install pyinstaller
    
    - name: Find espeak-ng-data path
      id: espeak-path
      run: |
        ESPEAK_PATH=$(python -c "import piper_phonemize; import os; print(os.path.join(os.path.dirname(piper_phonemize.__file__), 'espeak-ng-data'))")
        echo "path=$ESPEAK_PATH" >> $GITHUB_OUTPUT
    
    - name: Build ARM binary
      run: |
        pyinstaller \
          --add-data "${{ steps.espeak-path.outputs.path }}:piper_phonemize/espeak-ng-data" \
          --onefile \
          --name piper-arm \
          piper_main.py
    
    - name: Upload ARM binary
      uses: actions/upload-artifact@v4
      with:
        name: piper-arm-binary
        path: dist/piper-arm
